const APOLLO_CLIENT_URL =
  import.meta.env.VITE_APOLLO_CLIENT_URL || 'http://localhost:4000';

const VITE_DATABASE_PROJECT_URL = import.meta.env.VITE_DATABASE_PROJECT_URL;
const VITE_DATABASE_PUBLIC_API_KEY = import.meta.env
  .VITE_DATABASE_PUBLIC_API_KEY;

export {
  APOLLO_CLIENT_URL,
  VITE_DATABASE_PROJECT_URL,
  VITE_DATABASE_PUBLIC_API_KEY,
};
